CREATE TABLE [dbo].[Users]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Login] NVARCHAR(50) NOT NULL,
	[Password] VARBINARY(MAX) NOT NULL,
	[PasswordSalt] VARBINARY(MAX) NOT NULL,
	PRIMARY KEY CLUSTERED([Id]ASC)
);